export enum Parametros {
  // Hematología
  HEMOGLOBINA = "HEMOGLOBINA",
  HEMATOCRITO = "HEMATOCRITO",
  LEUCOCITOS = "LEUCOCITOS",
  NEUTROFILOS = "NEUTROFILOS",
  LINFOCITOS = "LINFOCITOS",
  PLAQUETAS = "PLAQUETAS",

  // Bioquímica
  GLUCOSA = "GLUCOSA",
  CREATININA = "CREATININA",
  UREA = "UREA",
  ACIDO_URICO = "ACIDO_URICO",
  BILIRRUBINA_TOTAL = "BILIRRUBINA TOTAL",
  BILIRRUBINA_DIRECTA = "BILIRRUBINA DIRECTA",
  TRANSAMINASAS = "TRANSAMINASAS",
  GOT_AST = "GOT_AST",
  GPT_ALT = "GPT_ALT",
  FOSFATASA_ALCALINA = "FOSFATASA_ALCALINA",
  GAMMA_GT = "GAMMA_GT",
  PROTEINAS_TOTALES = "PROTEINAS_TOTALES",
  ALBUMINA = "ALBUMINA",
  COLESTEROL_TOTAL = "COLESTEROL_TOTAL",
  COLESTEROL_HDL = "COLESTEROL_HDL",
  COLESTEROL_LDL = "COLESTEROL_LDL",
  TRIGLICERIDOS = "TRIGLICERIDOS",

  // Iones
  SODIO = "SODIO",
  POTASIO = "POTASIO",
  CLORO = "CLORO",
  CALCIO = "CALCIO",
  FOSFORO = "FOSFORO",
  MAGNESIO = "MAGNESIO",

  // Endocrinología
  TSH = "TSH",
  T4_LIBRE = "T4_LIBRE",

  // Metabolismo del hierro
  FERRITINA = "FERRITINA",
  HIERRO = "HIERRO",
  TRANSFERRINA = "TRANSFERRINA",

  // Marcadores inflamatorios
  PCR = "PCR"
}
